import fs from 'node:fs';
import path from 'node:path';
import type { MediaKind, ScriptDraft } from '../../shared/types';

export type MediaExt = 'mp4' | 'png';

export function safeSceneKey(sceneId: string): string {
  return sceneId.replace(/[^a-zA-Z0-9_-]/g, '_') || 'scene';
}

export function mediaExtFor(kind: MediaKind): MediaExt {
  return kind === 'image' ? 'png' : 'mp4';
}

export function sceneMediaDir(projectDir: string, kind: MediaKind): string {
  return path.join(projectDir, kind === 'image' ? 'images' : 'clips');
}

export function sceneMediaTarget(dir: string, sceneId: string, ext: MediaExt): string {
  return path.join(dir, `${safeSceneKey(sceneId)}.${ext}`);
}

function isUsable(filePath: string): boolean {
  try {
    return fs.statSync(filePath).size > 0;
  } catch {
    return false;
  }
}

// Scene ids have changed shape across app versions (`scene1`, `scene-1`, `scene-01`),
// so a project generated by an older build must still find the clips it paid for.
function candidateNames(sceneId: string, index: number, ext: MediaExt): string[] {
  const n = index + 1;
  const padded = String(n).padStart(2, '0');
  return [
    `${safeSceneKey(sceneId)}.${ext}`,
    `scene-${padded}.${ext}`,
    `scene-${n}.${ext}`,
    `scene${padded}.${ext}`,
    `scene${n}.${ext}`,
    `scene_${n}.${ext}`,
  ];
}

function trailingNumber(name: string): number {
  const groups = name.match(/(\d+)/g);
  return groups ? Number(groups[groups.length - 1]) : Number.MAX_SAFE_INTEGER;
}

function listMediaFiles(dir: string, ext: MediaExt): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((name) => name.toLowerCase().endsWith(`.${ext}`))
    .filter((name) => isUsable(path.join(dir, name)))
    .sort((a, b) => trailingNumber(a) - trailingNumber(b) || a.localeCompare(b))
    .map((name) => path.join(dir, name));
}

/**
 * Resolves the media file backing each scene, tolerating older naming schemes.
 * Returns null for scenes with no usable file.
 */
export function resolveSceneMedia(
  projectDir: string,
  script: ScriptDraft,
  kind: MediaKind
): (string | null)[] {
  const dir = sceneMediaDir(projectDir, kind);
  const ext = mediaExtFor(kind);
  const scenes = script.scenes;

  const resolved: (string | null)[] = scenes.map((scene, index) => {
    for (const name of candidateNames(scene.id, index, ext)) {
      const candidate = path.join(dir, name);
      if (isUsable(candidate)) return candidate;
    }
    return null;
  });

  if (resolved.every(Boolean)) return resolved;

  // No name matched: the script was regenerated with new scene ids while the
  // media on disk still carries the old ones. Pair by position, but only when
  // the counts line up so a clip can't be attached to the wrong scene.
  const files = listMediaFiles(dir, ext);
  if (files.length !== scenes.length) return resolved;

  const claimed = new Set(resolved.filter((item): item is string => Boolean(item)));
  const spare = files.filter((file) => !claimed.has(file));
  let cursor = 0;
  return resolved.map((item) => item ?? spare[cursor++] ?? null);
}

/**
 * Renames resolved media to the canonical `<sceneId>.<ext>` so later lookups
 * no longer depend on the legacy-name fallback.
 */
export function adoptSceneMedia(
  projectDir: string,
  script: ScriptDraft,
  kind: MediaKind
): void {
  const dir = sceneMediaDir(projectDir, kind);
  const ext = mediaExtFor(kind);
  const resolved = resolveSceneMedia(projectDir, script, kind);
  if (resolved.some((item) => !item)) return;

  const targets = script.scenes.map((scene) => sceneMediaTarget(dir, scene.id, ext));
  if (resolved.every((item, index) => item === targets[index])) return;

  // Two-phase rename so sources and targets can overlap without clobbering.
  const temps = resolved.map((source, index) => {
    const temp = path.join(dir, `__adopt_${index}.${ext}`);
    fs.renameSync(source as string, temp);
    return temp;
  });
  temps.forEach((temp, index) => {
    fs.renameSync(temp, targets[index]);
  });
}

export function collectSceneMediaPaths(
  projectDir: string,
  script: ScriptDraft,
  kind: MediaKind
): string[] {
  const resolved = resolveSceneMedia(projectDir, script, kind);
  const missing = resolved.findIndex((item) => !item);
  if (missing !== -1) {
    throw new Error(
      `Thiếu ${kind === 'image' ? 'ảnh' : 'clip'} cho cảnh ${missing + 1}. Hãy Generate trước.`
    );
  }
  return resolved as string[];
}
