export const IPC = {
  getSettings: 'settings:get',
  saveSettings: 'settings:save',
  getKeys: 'keys:get',
  saveKeys: 'keys:save',
  testSnapgen: 'test:snapgen',
  testOpenAI: 'test:openai',
  generateScript: 'openai:script',
  startGenerate: 'job:start',
  remuxProject: 'job:remux',
  jobProgress: 'job:progress',
  openPath: 'shell:openPath',
  showItemInFolder: 'shell:showItem',
  exportVideo: 'job:export',
  exportMedia: 'job:exportMedia',
  getModels: 'models:list',
  listProjects: 'projects:list',
  getProject: 'projects:get',
  createProject: 'projects:create',
  renameProject: 'projects:rename',
  deleteProject: 'projects:delete',
  saveProjectDraft: 'projects:saveDraft',
} as const;
